### ISSUE TITLE
Info.plist is not included in project

### ISSUE THREAD

**Issue by marcuseckert** [pointfreeco/swift-gen#11]
It looks like the Info.plist isn't included in the project so frameworks are built without them causing trouble with Carthage integration.

**Comment by stephencelis** [comment]
Ha we were actually considering dropping Carthage support in other projects since Xcode has SPM support these days. Anything preventing you from using SPM? Happy to accept a PR if it makes sense!

**Comment by marcuseckert** [comment]
Thanks for getting back to me. SPM just isn't as well supported yet as Carthage and adding PRs to all the places where the package files are missing seems like a doomed endeavour (not to mention a lengthy one). So for the time being carthage is our way to go. I've added the PR for the plists.

**Comment by stephencelis** [comment]
Just to clarify, is it not possible to use both? E.g. SwiftPM for SwiftPM-supported dependencies and Carthage for the rest?

**Comment by marcuseckert** [comment]
I'm guessing it is, I'm still working on getting rid of Cocoapods, though :p So, I'd rather not have three dependency managers:) The plan is to have Carthage replace Cocoapods for now...

**Comment by stephencelis** [comment]
Closing along with #12.
