### ISSUE TITLE
Build fails on DTK

### ISSUE THREAD

**Issue by finestructure** [pointfreeco/swift-gen#14]
Hi Brandon, Stephen,

just a little heads up: Gen is currently failing to build on macOS/ARM:

```
env DEVELOPER_DIR="/Applications/Xcode_12_beta_6.app" xcrun swift build
/Users/builder/Downloads/checkout/Sources/Gen/Gen.swift:279:30: error: 'Float80' is unavailable: Float80 is not available on target platform.
extension Gen where Value == Float80 {
                             ^~~~~~~
Swift.Float80:2:23: note: 'Float80' has been explicitly marked unavailable here
@frozen public struct Float80 {
                      ^
/Users/builder/Downloads/checkout/Sources/Gen/Gen.swift:285:40: error: type 'Value' does not conform to protocol 'Comparable'
  public static func float80(in range: ClosedRange<Value>) -> Gen {
                                       ^
/Users/builder/Downloads/checkout/Sources/Gen/Gen.swift:286:12: error: type of expression is ambiguous without more context
    return Gen { rng in .random(in: range, using: &rng) }
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[5/5] Compiling Gen Zip.swift
```

(both 12b4 and 12b6). See also: https://swiftpackageindex.com/pointfreeco/swift-gen/builds

Not sure what the best fix here would be - perhaps exclude the `Float80` overload on ARM for now?

**Comment by mbrandonw** [comment]
Yeah we've started to see this too :/

Weirdly we even addressed this perviously in this PR https://github.com/pointfreeco/swift-gen/pull/6, and that worked for awhile.

I'm going to PR removing `Float80` for now.

**Comment by mbrandonw** [comment]
Hey @finestructure we just merged #15, can you see if that works better for you?

**Comment by finestructure** [comment]
Excellent, both ARM builds green now for `main`! ✅ https://swiftpackageindex.com/pointfreeco/swift-gen/builds

Thank you :)

**Comment by mbrandonw** [comment]
Awesome, we'll cut a release today!

**Comment by finestructure** [comment]
By the way: I noticed that the watchOS builds are marked as failing in SPI as well. This is because it isn't finding your custom scheme and the default scheme is trying to build the tests, which fails on watchOS. We're currently trialling a little manifest file that you could add to get the watchOS builds to pass.

Just add the following `.spi.yml` file to the repo:

```yaml
version: 1
builder:
  configs:
  - platform: watchos
    scheme: Gen_watchOS
```

**Comment by stephencelis** [comment]
@finestructure Interesting! I've added that on `main` so we'll see what happens. Relatedly, any idea why watchOS _and_ tvOS are failing here?

https://swiftpackageindex.com/pointfreeco/swift-composable-architecture/builds

We definitely support them, so I wonder if we need to make any configuration like the YAML above.

**Comment by finestructure** [comment]
tvos is failing with this:

```

/Users/builder/builds/pMpxem39/3/finestructure/swiftpackageindex-builder/spi-builder-workspace/Tests/ComposableCoreMotionTests/ComposableCoreMotionTests.swift:31:14: error: use of unresolved identifier 'Attitude'
    let q3 = Attitude(quaternion: .init(x: 0, y: 0, z: 1, w: 0))
             ^~~~~~~~
```

(you can click through to the logs from the cells, https://swiftpackageindex.com/builds/7E4238D7-37A2-4809-8A64-96B3B6EA2EF0)

and watchos is trying to compile the tests:

```

/Users/builder/builds/pMpxem39/8/finestructure/swiftpackageindex-builder/spi-builder-workspace/Tests/ComposableCoreLocationTests/ComposableCoreLocationTests.swift:2:8: error: failed to load module 'XCTest'
import XCTest
       ^
```

So the latter would also benefit from a custom scheme. tvos seems to be a genuine failure? Or maybe our compile command is doing something differently?

We're showing that on the build details page as well. Not at a computer right now, so I can run it locally :)

**Comment by stephencelis** [comment]
Ah I see the failures now 😅 Thanks!

**Comment by finestructure** [comment]
Nice, all green now for main/5.1-5.3! https://swiftpackageindex.com/pointfreeco/swift-gen/builds 🎉

BTW, I just noticed that the Swift version badge in the README is showing 5.1 only. Not sure if you’ve seen this but you can copy a badge link for Swift version and platform compatibility from the SPI package page (under the tables). It’ll keep in sync with the builds.

**Comment by stephencelis** [comment]
@finestructure We still need to bump a release, at which point we'll update the README and we should def change that part. Thanks!

**Comment by stephencelis** [comment]
Let's give that badge a test drive: [![](https://img.shields.io/endpoint?url=https%3A%2F%2Fswiftpackageindex.com%2Fapi%2Fpackages%2Fpointfreeco%2Fswift-gen%2Fbadge%3Ftype%3Dswift-versions)](https://swiftpackageindex.com/pointfreeco/swift-gen)

Cool!
