### ISSUE TITLE
iOS target does not compile

### ISSUE THREAD

**Issue by mbuchetics** [pointfreeco/swift-gen#5]
`Gen_iOS` fails due to `Gen.swift:278:30: 'Float80' is unavailable: Float80 is only available on non-Windows x86 targets.` 

All other targets work fine.

**Comment by mbrandonw** [comment]
Thanks for the issue! I opened a PR [here](https://github.com/pointfreeco/swift-gen/pull/6) and will discuss with Stephen soon.

**Comment by mbrandonw** [comment]
@mbuchetics we've merged that PR and cut a new 0.1.1 release https://github.com/pointfreeco/swift-gen/releases/tag/0.1.1. Thanks again!

**Comment by mbuchetics** [comment]
Works great, thank you!
